### ISSUE TITLE
Still getting deprecation notice for implicit conversion even after updating to v1.1.9

### ISSUE THREAD

**Issue by betaSavvy** [hidehalo/nanoid-php#20]
## Detailed description

After updating to 1.1.9, I am still getting this deprecation notice.

```shell
Implicit conversion from float 59.746165961027145 to int loses precision in /vendor/hidehalo/nanoid-php/src/Client.php on line 113
```

Code to reproduce
```php
use Hidehalo\Nanoid\Client as Nanoid;

$this->nanoid = new Nanoid();
$this->nanoid->generateId(10)
```
## Context

Using this to generate a default uniqueID for editorjs blocks from php

## Possible implementation

Explicit `int` casting

## Your environment

* PHP 8.1.1
* hidehalo/nanoid-php 1.1.9

**Comment by hidehalo** [comment]
Hello @betaSavvy, I'm glad for your issue report !

### Reason

I think that deprecation notice out because of this line:

```php
/**
 * @var float|int $rand
 */
// line: 113
$id .= $this->alphabet[$rand*64 | 0];
```

value of variable `$rand`'s data type is unstable, it maybe is a `float` type value.
 
### Advice

My advice is make explicit int casting for expression of variable `$rand` assignment:

```php
// line: 112
 $rand = intval(mt_rand()/(mt_getrandmax() + 1));
```

Would you like help us to fix this issue? If not, I will fix this laster. 

I'm looking forward to your feedback, thank you!

**Comment by betaSavvy** [comment]
Hi @hidehalo Sure will do a PR in a bit.

**Comment by hidehalo** [comment]
> Hi @hidehalo Sure will do a PR in a bit.

Wait for your PR! xD

**Comment by hidehalo** [comment]
Thanks for the contribution from @betaSavvy. 😃 We can use version [1.1.10](https://github.com/hidehalo/nanoid-php/releases/tag/1.1.10) to stay away from deprecation notice for now.
